### ISSUE TITLE
Faceted Browsers mustreact directly to facet selection

### ISSUE THREAD

**Issue by jimmccusker** [paulopinheiro1234/hadatac#105]
Looking at just about every faceted browser in the world, from Amazon.com and Kayak.com to Refine and Exhibit, when data values are selected the UI updates immediately. HADATAC does not do this, and is counter-intuitive.

**Comment by paulopinheiro1234** [comment]
We were using the desired approach in the past, but it did not allow for the user to select ANDs of the same type of concept. For example, if you have child BMI, mother BMI and father BMI, and you want to select child BMI and father BMI, but not the mother API. In this case, the UI needs to allow the selection of child BMI and father BMI before it reacts to the selection.

**Comment by paulopinheiro1234** [comment]
If someone sees a different way of handling the issue, please let us know.

**Comment by paulopinheiro1234** [comment]
We are closing this issue because we cannot see a way of supporting BOTH direct react to selection AND search of disjoint concepts.
