### ISSUE TITLE
Units ontology (UO) prefix is incorrect

### ISSUE THREAD

**Issue by jimmccusker** [paulopinheiro1234/hadatac#110]
HADATAC uses `http://geneontology.org/GO.format.obo-1_2.shtml#`. That's not a prefix for anything. The correct URI prefix is `http://purl.obolibrary.org/obo/`.

**Comment by xkortex** [comment]
This is present in both CPP data and also CBIS data. 

Also, I'm not sure if all HTTP URIs are supposed to resolve, but a lot of these in both datasets fail to resolve to valid endpoints, e.g. the geneontology one above, http://hadatac.org/kb/case, hadatac.org/kb/hbgd, etc.

**Comment by johnsm21** [comment]
As of HHear we are using the correct prefix URI for UO.
