### ISSUE TITLE
Timestamp formatting problems

### ISSUE THREAD

**Issue by xkortex** [paulopinheiro1234/hadatac#112]
It was discovered in DJ that [line charts were not rendering right](https://github.com/RPI-CASE/DataJourney-Dashboard/issues/672). Upon further investigation, it was discovered that there were several issues in the (Solr) data. 

In the CBIS data (seed: hadatac_solr.cbis.zip), the time is not always in isoformat, e.g. `"2/7/17 10:25"`. This causes sorting to fail. 

In the Gates CPP data (seed: hadatac_solr.gates.09-07-2017.zip), all (1344532) records have the timestamp "+292278994-08-17T07:12:55.807Z". This corresponds to `DateTime.parse(new DateTime(Long.MAX_VALUE).toString());`. Technically isoformat, but otherwise invalid and neither is it a "null time" value, since many date parsers can't assess this date. Emptystring `""`, `null`, `NaN` or `NaT` would be much easier to catch. 

Also in Gates CPP, the "named_time" field is not consistently formatted. In some cases, it would appear that an ordinal system (1,2,..99) is used, but in others, the values are large decimal (51000940.0, 51000420.0, 51000430.0). 

This also means there is no valid absolute time information in the (CPP) dataset. 

[Solr supports multiple native datetime formats](https://lucene.apache.org/solr/guide/6_6/working-with-dates.html#working-with-dates), which would be the ideal storage format. However, iso_instant() format would also be fine.  

Steps to reproduce:
I'm running off of the most recent version of https://github.com/RPI-CASE/DataJourney-Dashboard/blob/master/docker-compose.dev.yml . Just seeded with the aforementioned datasets and queried via Solr endpoint.

**Comment by xkortex** [comment]
Can we please use [ISO duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations) for timedeltas / durations / anonymized time offsets? Thanks.

**Comment by paulopinheiro1234** [comment]
ISO format has been in use for a while.
