### ISSUE TITLE
entity_uri == "http://www.w3.org/2002/07/owl#Class"

### ISSUE THREAD

**Issue by xkortex** [paulopinheiro1234/hadatac#114]
In `hadatac_solr.gates.09-07-2017`, the majority (1342260 of 1344532) of the contents of field `entity_uri` == "http://www.w3.org/2002/07/owl#Class", which is the top level most-abstract class.

**Comment by chastk** [comment]
This is expected for the summary data, and reflects that hadatac was not designed to service this sort of data, unfortunately. This is part of why we're moving towards hosting the summary data on Satoru instead.
