### ISSUE TITLE
Create code for checking and testing SDDs

### ISSUE THREAD

**Issue by dlmcguinness** [paulopinheiro1234/hadatac#120]
from the text in https://docs.google.com/document/d/1VMdkUkXSwIqmvgqy_lTiRWYdEMSNpIhHCbDE5dFdq3U/edit  execute task 7 added under 5/3
@Robin Also, we need to have the SDD verification done during SDD ingestion, and that verification needs to check the following (we have had problems with all these issues ((a), (b) and (c)) during the ingestion of 1432 and 1448): 
if URIs in SDDs are resolvable against existing knowledge graph; 
if every namespace mentioned in an SDD is registered in HADatAc; and 
if every attribute used in an SDD has a path to a subclass of hasco:StudyIndicator
if DASAs and DASOS derived from an Excel SDD are well-formed (robin-feature branch)
every DASO must have a role. This is something that @Robin can write code to verify, and @hensantos can update the DAS viewer to show DASOs' roles 
Provide a set of incorrect sdds to be used for testing.  Where are those sdds?
Perform a test of the sdds on box against these criteria   (these are the 4 new studies)  https://mountsinai.app.box.com/s/w7o0ddfdatuihqeck6ehn5mrg9v1o130/folder/48692787236

**Comment by paulopinheiro1234** [comment]
Done
