### ISSUE TITLE
adjust installation script, develop update script, and develop uninstall script

### ISSUE THREAD

**Issue by paulopinheiro1234** [paulopinheiro1234/hadatac#14]
installation script needs to be adjusted due to project refactoring.

installation script should not run if associated solr instances are installed, and the uninstall script should be used to delete associated solr instances.

update script should update hadatac software without affecting associated solr instances

**Comment by hansidm** [comment]
Install script is updated for Linux,
Need to develop update.

**Comment by rashidsabbir** [comment]
Uninstall or update scripts have not yet been created...

**Comment by johnsm21** [comment]
Install scripts are up to date but uninstall scripts don't exist.

**Comment by johnsm21** [comment]
Added an uninstall script
