### ISSUE TITLE
triple store verification

### ISSUE THREAD

**Issue by paulopinheiro1234** [paulopinheiro1234/hadatac#15]
core hasneto concepts  (vstoi.instrument, vstoi.platform, oboe.entity, oboe.characteristic) need to be loaded in the triple store at all time, and the console should help administrators to load these concepts in case they are unavailable.

**Comment by paulopinheiro1234** [comment]
some requirements that need to be verified when hadatac starts:

- hadata needs to have a solr installation

- solr installation needs to be up and running

- main admin password needs to be different than "admin"

- one user needs to be registered

- key ontologies need to be loaded (and they must include top-level classes for all key hasneto concepts)

**Comment by bfeaginjr** [comment]
Paulo, 

there are some very urgent lab priorities this week and I won't be able to work on this after all until those are taken care of. Also I've requested permission from Anna to post the visualization code to the public realm but I haven't received a response. You may wish to speak with her next time you see her maybe to expedite this inquiry? I can't move forward without that permission, unfortunately.

-Benjamin Feagin Jr., Ph.D. Candidate, BFA, LC
-1-518-833-2933
http://www.linkedin.com/in/bfeagin/

----- Reply message -----

**Comment by rashidsabbir** [comment]
All of the issues discussed in this thread have since been addressed
