### ISSUE TITLE
Configuration File Unification/Absolute Paths

### ISSUE THREAD

**Issue by Aaron0372** [paulopinheiro1234/hadatac#155]
The hadatac.conf file should now contain the autoccsv.config and gui.config files' information. Hadatac should pull configuration settings found previously in autoccsv.config and gui.config from the hadatac.conf file. File paths found in the hadatac.conf should be absolute paths to avoid directory creation/access in the incorrect path.
A second install shell script for hadatac (install_hadatac2) should allow a "conf" directory outside of hadatac to be created and/or loaded into the hadtac/conf directory.

**Comment by paulopinheiro1234** [comment]
Done and tested
