### ISSUE TITLE
#167 Browse Metadata Produces Null Pointer Exception in HHEAR Branch

### ISSUE THREAD

**Issue by chipmasters** [paulopinheiro1234/hadatac#167]
In Mount Sinai QA Environment (running the HHEAR branch in Production) when I select "Browse Metadata" from the top menu row and then select any item under "Browse Metadata" section on the resulting page (below Browse Ontologies), I get a null pointer exception.

Error :(
java.lang.NullPointerException

@paulopinheiro1234 Is it possible to configure Prod to grey the "Browse Metadata" option out on the home page so users can't access the error path?

**Comment by paulopinheiro1234** [comment]
This was caused by MSSM QA enviroment's Blazegraph not having the correct name for the user namespace. It is unclear how QA environment got corrupted.
