### ISSUE TITLE
Create Example Folder (hadatac.example)

### ISSUE THREAD

**Issue by paulopinheiro1234** [paulopinheiro1234/hadatac#8]
We need to include examples of the following:

1) CSV files (from Henrique)
2) CCSV files derived from (1) (from Henrique)
3) HASNetO spreadsheet example with the metadata for (2) (from Paulo)
4) HASNetO spreadsheet template (from Paulo)

**Comment by hansidm** [comment]
Is this structure ok?
- hadatac.example
-- csv
-- ccsv

**Comment by paulopinheiro1234** [comment]
Sure. Please go ahead and include a hasneto folder as well.

**Comment by hansidm** [comment]
Example files and Data Loader integrated into Play are coming tomorrow.

**Comment by hansidm** [comment]
example folder is now on master branch.
