### ISSUE TITLE
HaDatac installation

### ISSUE THREAD

**Issue by mohamedaly** [paulopinheiro1234/hadatac#92]
Naomi tried to upload HADatAc on her mac following the wiki instructions. Everything is working until run HADatAc at the end. Then I get this error (see the attached image/screenshot of terminal window):
"UNRESOLVED DEPENDENCIES"
![screen shot 2015-11-04 at 9 26 45 am](https://cloud.githubusercontent.com/assets/3907607/10943058/d5365270-82e0-11e5-82c7-8c200c3a3436.png)

**Comment by rashidsabbir** [comment]
Installation script has since been updated
